#!/bin/sh

# The MIT License (MIT)
# 
# Copyright (c) 2014 Sebastian Gładki
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# -----------------------------------
#    ADJUST STUFF BELOW IF NEEDED
# -----------------------------------

# -----------------------------------
# If you're not using Maemo on the
# N900, you might want to adjust this
# because there's no autodetection 
# for this stuff YET.
# -----------------------------------
M_WM="Matchbox"
M_DE="Hildon"

# -----------------
# You have to set this stuff manually.
# This will look like: Distro (BaseDistro) 
# so: Maemo (Debian)
# The first part has to be set manually.
# The second part is detected by lsb_release
# -----------------

M_DISTRO1="Maemo"
M_DISTRO=$(echo "$M_DISTRO1 ($M_DISTRO2)")

# --------------------------------------
# This stuff is detected automatically
# but might not always work as expected.
# --------------------------------------

M_SHELL=$(echo $SHELL)
M_TERM=$(echo $TERM)
#M_SHELL="/bin/zsh4"
#M_TERM="LXTerminal"

# ------
# COLORS
# ------
COLCLR="\x1b[0m"
COL1="\x1b[1;33m"
COL2="\x1b[1;30m"

# ----------
# ASCII LOGO
# ----------

M_LOGO01="${COL2}      ########${COL1}             ????????      ${COLCLR}"
M_LOGO02="${COL2}    #############${COL1}        ?????????????   ${COLCLR}"
M_LOGO03="${COL2}  ######    ######${COL1}     ??????    ??????  ${COLCLR}"
M_LOGO04="${COL2} ####          #####${COL1} ??????        ????? ${COLCLR}"
M_LOGO05="${COL2}####            ####${COL1}?????            ????${COLCLR}"
M_LOGO06="${COL2}####             ##${COL1}????   ???????????????${COLCLR}"
M_LOGO07="${COL2}####               ${COL1}????   ???????????????${COLCLR}"
M_LOGO08="${COL2}####             ##${COL1} ?????                ${COLCLR}"
M_LOGO09="${COL2} ####          #####${COL1} ?????          ???? ${COLCLR}"
M_LOGO10="${COL2}  #####      ########${COL1}  ?????      ?????  ${COLCLR}"
M_LOGO11="${COL2}   ############## ####${COL1}  ??????????????   ${COLCLR}"
M_LOGO12="${COL2}     ##########${COL1}            ?????????     ${COLCLR}"
M_LOGO13="                                         "

#TODO: Add the disk space counters so this can be used.
#M_LOGO14="                                         "

# -----------------------------------
#    ADJUST STUFF ABOVE IF NEEDED
# -----------------------------------
M_DISTRO2=$(lsb_release -si)
M_HOST=$(uname -n)
M_KERNEL=$(uname -r)

M_UPTIME=$(uptime|cut -d" " -f4-|sed 's/\, *0.*//')
M_PACKAGES=$(dpkg --get-selections | grep -v deinstall | wc -w)
M_CPU=$(cat /proc/cpuinfo | grep "Hardware" | awk -F: '{print $2}')

M_RAMTOTAL=$(free | grep "Mem" | awk -F: '{print $2}' | awk '{print $1}')
M_RAMTOTAL_MB=$(($M_RAMTOTAL/1024))
M_RAMUSED=$(free | grep "Mem" | awk -F: '{print $2}' | awk '{print $2}')
M_RAMUSED_MB=$(($M_RAMUSED/1024))

M_SWAPTOTAL=$(free | grep "Swap" | awk -F: '{print $2}' | awk '{print $1}')
M_SWAPTOTAL_MB=$(($M_SWAPTOTAL/1024))
M_SWAPUSED=$(free | grep "Swap" | awk -F: '{print $2}' | awk '{print $2}')
M_SWAPUSED_MB=$(($M_SWAPUSED/1024))

#Print Everything
echo -e "${M_LOGO01} ${COL1}User:${COLCLR} $USER"
echo -e "${M_LOGO02} ${COL1}Hostname:${COLCLR} $M_HOST"
echo -e "${M_LOGO03} ${COL1}Kernel:${COLCLR} $M_KERNEL"
echo -e "${M_LOGO04} ${COL1}Distro:${COLCLR} $M_DISTRO"
echo -e "${M_LOGO05} ${COL1}Uptime:${COLCLR} $M_UPTIME"
echo -e "${M_LOGO06} ${COL1}Window Manager:${COLCLR} $M_WM"
echo -e "${M_LOGO07} ${COL1}Desktop Environment:${COLCLR} $M_DE"
echo -e "${M_LOGO08} ${COL1}Shell:${COLCLR} $M_SHELL"
echo -e "${M_LOGO09} ${COL1}Terminal:${COLCLR} $M_TERM"
echo -e "${M_LOGO10} ${COL1}Packages:${COLCLR} $M_PACKAGES"
echo -e "${M_LOGO11} ${COL1}CPU:${COLCLR}$M_CPU"
echo -e "${M_LOGO12} ${COL1}Ram:${COLCLR} $M_RAMUSED_MB MB / $M_RAMTOTAL_MB MB"
echo -e "${M_LOGO13} ${COL1}Swap:${COLCLR} $M_SWAPUSED_MB MB / $M_SWAPTOTAL_MB MB"

#TODO: rootfs, mydocs, home space status
#echo "${M_LOGO14} Disk: #"
